spring:
  application:
    name: backend-test-java
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost}:5432/${POSTGRES_DATABASE:parking_db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8000

springdoc:
  swagger-ui:
    operationsSorter:
      method: